// GENERATED by scripts/gen_after_prayer.py — لا تعدّل يدوياً.
// المصدر: «حصن المسلم» (سعيد بن علي بن وهف القحطاني) — «الأذكار بعد السلام من الصلاة».
// آية الكرسي والمعوذات من النص العثماني الموثّق `verified_quran.dart`.

import 'general_ruqyah_data.dart';
import 'verified_quran.dart';

/// أذكار ما بعد الصلاة المفروضة بترتيب «حصن المسلم».
List<GeneralRuqyahItem> afterPrayerItems() => [
    GeneralRuqyahItem(
      title: 'الاستغفار',
      repeat: 3,
      source: 'رواه مسلم',
      blocks: [
        RuqyahBlock(lines: ['أَسْتَغْفِرُ اللَّهَ']),
      ],
    ),
    GeneralRuqyahItem(
      title: 'اللهم أنت السلام',
      repeat: 1,
      source: 'رواه مسلم',
      blocks: [
        RuqyahBlock(lines: ['اللَّهُمَّ أَنْتَ السَّلاَمُ، وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَالْإِكْرَامِ']),
      ],
    ),
    GeneralRuqyahItem(
      title: 'لا مانع لما أعطيت',
      repeat: 1,
      source: 'متفق عليه',
      blocks: [
        RuqyahBlock(lines: ['لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، اللَّهُمَّ لاَ مَانِعَ لِمَا أَعْطَيْتَ، وَلاَ مُعْطِيَ لِمَا مَنَعْتَ، وَلاَ يَنْفَعُ ذَا الْجَدِّ مِنْكَ الجَدُّ']),
      ],
    ),
    GeneralRuqyahItem(
      title: 'لا حول ولا قوة إلا بالله',
      repeat: 1,
      source: 'رواه مسلم',
      blocks: [
        RuqyahBlock(lines: ['لَا إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ، وَلَهُ الْحَمدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ. لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ، وَلاَ نَعْبُدُ إِلاَّ إِيَّاهُ، لَهُ النِّعْمَةُ وَلَهُ الْفَضْلُ وَلَهُ الثَّنَاءُ الْحَسَنُ، لَا إِلَهَ إِلاَّ اللَّهُ مُخْلِصِينَ لَهُ الدِّينَ وَلَوْ كَرِهَ الكَافِرُونَ']),
      ],
    ),
    GeneralRuqyahItem(
      title: 'التسبيح',
      repeat: 33,
      source: 'رواه مسلم',
      blocks: [
        RuqyahBlock(lines: ['سُبْحَانَ اللَّهِ']),
      ],
    ),
    GeneralRuqyahItem(
      title: 'التحميد',
      repeat: 33,
      source: 'رواه مسلم',
      blocks: [
        RuqyahBlock(lines: ['الْحَمْدُ لِلَّهِ']),
      ],
    ),
    GeneralRuqyahItem(
      title: 'التكبير',
      repeat: 33,
      source: 'رواه مسلم',
      blocks: [
        RuqyahBlock(lines: ['اللَّهُ أَكْبَرُ']),
      ],
    ),
    GeneralRuqyahItem(
      title: 'تمام المئة',
      repeat: 1,
      source: 'رواه مسلم',
      note: 'يُختم به التسبيح والتحميد والتكبير',
      blocks: [
        RuqyahBlock(lines: ['لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ']),
      ],
    ),
    GeneralRuqyahItem(
      title: 'آية الكرسي',
      subtitle: 'البقرة (٢٥٥)',
      repeat: 1,
      isQuran: true,
      source: 'رواه النسائي في عمل اليوم والليلة',
      blocks: [
        RuqyahBlock(
          heading: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
          lines: verseLines(ayatAlKursi),
        ),
      ],
    ),
    GeneralRuqyahItem(
      title: 'المعوذات',
      subtitle: 'الإخلاص والفلق والناس',
      repeat: 1,
      isQuran: true,
      source: 'رواه أبو داود والنسائي والترمذي',
      note: 'تُقرأ مرة بعد كل صلاة مفروضة، وتُقرأ ثلاثاً ضمن أذكار الصباح والمساء',
      blocks: muawwidhatBlocks,
    ),
    GeneralRuqyahItem(
      title: 'التهليل عشراً',
      repeat: 10,
      source: 'رواه الترمذي وأحمد',
      note: 'بعد صلاتي المغرب والصبح',
      blocks: [
        RuqyahBlock(lines: ['لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ يُحْيِي وَيُمِيتُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ']),
      ],
    ),
    GeneralRuqyahItem(
      title: 'علماً نافعاً',
      repeat: 1,
      source: 'رواه ابن ماجه',
      note: 'بعد السلام من صلاة الفجر',
      blocks: [
        RuqyahBlock(lines: ['اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْماً نافِعاً، وَرِزْقاً طَيِّباً، وَعَمَلاً مُتَقَبَّلاً']),
      ],
    ),
  ];
