#!/usr/bin/env python3
"""Generate lib/data/quran_index.dart and lib/data/quran_extracts.dart.

Sources (download both from tanzil.net, never edit by hand):
  assets/quran/quran-uthmani.txt  - Tanzil Uthmani 1.1, options: pause marks,
      sajdah signs, superscript alef (NO tatweel, NO rub-el-hizb), txt-2 format
      https://tanzil.net/pub/download/index.php?quranType=uthmani&marks=true&sajdah=true&alef=true&outType=txt-2&agree=true
  quran-data.xml                  - https://tanzil.net/res/text/metadata/quran-data.xml

Usage:  python3 scripts/gen_quran_data.py path/to/quran-data.xml
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QURAN = ROOT / 'assets/quran/quran-uthmani.txt'

AR_DIGITS = str.maketrans('0123456789', '٠١٢٣٤٥٦٧٨٩')


def load_quran():
    t = {}
    for line in QURAN.read_text(encoding='utf-8').splitlines():
        if not line or line.startswith('#'):
            continue
        s, a, txt = line.split('|', 2)
        t[(int(s), int(a))] = txt
    basmala = t[(1, 1)] + ' '
    for (s, a), txt in list(t.items()):
        if a == 1 and s not in (1, 9) and txt.startswith(basmala):
            t[(s, a)] = txt[len(basmala):]
    return t, basmala.strip()


def dart_str(s: str) -> str:
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def gen_index(xml_path):
    root = ET.parse(xml_path).getroot()
    suras = root.find('suras').findall('sura')
    juzs = root.find('juzs').findall('juz')
    out = [
        '// GENERATED by scripts/gen_quran_data.py from Tanzil quran-data.xml — DO NOT EDIT.',
        '// Source: Tanzil Project (tanzil.net), CC BY 3.0.',
        '',
        'class SurahInfo {',
        '  final int number;',
        '  final String name;',
        '  final int ayahCount;',
        '  final bool meccan;',
        '  const SurahInfo(this.number, this.name, this.ayahCount, this.meccan);',
        '}',
        '',
        '/// (surah, ayah) where each of the 30 juz starts.',
        'class JuzStart {',
        '  final int juz;',
        '  final int surah;',
        '  final int ayah;',
        '  const JuzStart(this.juz, this.surah, this.ayah);',
        '}',
        '',
        'const List<SurahInfo> kSurahs = [',
    ]
    total = 0
    for s in suras:
        n, ay = int(s.get('index')), int(s.get('ayas'))
        total += ay
        meccan = 'true' if s.get('type') == 'Meccan' else 'false'
        out.append(f"  SurahInfo({n}, {dart_str(s.get('name'))}, {ay}, {meccan}),")
    out.append('];')
    out.append('')
    out.append(f'const int kTotalAyat = {total};')
    out.append('')
    out.append('const List<JuzStart> kJuzStarts = [')
    for j in juzs:
        out.append(f"  JuzStart({j.get('index')}, {j.get('sura')}, {j.get('aya')}),")
    out.append('];')
    (ROOT / 'lib/data/quran_index.dart').write_text('\n'.join(out) + '\n', encoding='utf-8')
    return len(suras), total


# Verse ranges used by «رقى حسب الحالة» (see lib/data/ruqyah_types_data.dart).
EXTRACTS = {
    'arafSihr': (7, 117, 119),   # الأعراف ١١٧-١١٩
    'yunusSihr': (10, 79, 82),   # يونس ٧٩-٨٢
    'tahaSihr': (20, 65, 69),    # طه ٦٥-٦٩
}


def gen_extracts(t):
    out = [
        '// GENERATED by scripts/gen_quran_data.py from assets/quran/quran-uthmani.txt',
        '// (Tanzil Uthmani 1.1) — DO NOT EDIT. test/quran_asset_test.dart re-checks',
        '// every line against the bundled asset.',
        '',
        '/// A contiguous verse range, text exactly as in the Tanzil asset.',
        'class QuranExtract {',
        '  final int surah;',
        '  final int from;',
        '  final int to;',
        '  final List<String> verses;',
        '  const QuranExtract(this.surah, this.from, this.to, this.verses);',
        '}',
        '',
    ]
    for name, (s, a, b) in EXTRACTS.items():
        out.append(f'const {name} = QuranExtract({s}, {a}, {b}, [')
        for i in range(a, b + 1):
            out.append(f'  {dart_str(t[(s, i)])},')
        out.append(']);')
        out.append('')
    (ROOT / 'lib/data/quran_extracts.dart').write_text('\n'.join(out), encoding='utf-8')


if __name__ == '__main__':
    t, _ = load_quran()
    assert len(t) == 6236, len(t)
    n, total = gen_index(sys.argv[1])
    assert (n, total) == (114, 6236), (n, total)
    gen_extracts(t)
    print('ok: 114 surahs, 6236 ayat; extracts:', ', '.join(EXTRACTS))
