#!/usr/bin/env python3
"""Generate every Quran data file of the app from the one pinned Tanzil asset:
lib/data/quran_index.dart, quran_extracts.dart, quran_data.dart, verified_quran.dart.

Sources (download both from tanzil.net, never edit by hand):
  assets/quran/quran-uthmani.txt  - Tanzil Uthmani 1.1, options: pause marks,
      sajdah signs, superscript alef (NO tatweel, NO rub-el-hizb), txt-2 format
      https://tanzil.net/pub/download/index.php?quranType=uthmani&marks=true&sajdah=true&alef=true&outType=txt-2&agree=true
  quran-data.xml                  - https://tanzil.net/res/text/metadata/quran-data.xml

Also generates lib/data/quran_data.dart (full Al-Anfal, Ad-Dukhan, As-Saffat,
Al-Haqqah for the written ruqyah) byte-for-byte from the asset.

Usage:  python3 scripts/gen_quran_data.py [path/to/quran-data.xml]
        (without the XML only the verse files are regenerated)
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QURAN = ROOT / 'assets/quran/quran-uthmani.txt'

AR_DIGITS = str.maketrans('0123456789', '٠١٢٣٤٥٦٧٨٩')


def load_quran():
    t = {}
    for line in QURAN.read_text(encoding='utf-8').splitlines():
        if not line or line.startswith('#'):
            continue
        s, a, txt = line.split('|', 2)
        t[(int(s), int(a))] = txt
    basmala = t[(1, 1)]
    head = [skeleton(w) for w in basmala.split(' ')]
    for s in range(2, 115):
        words = t[(s, 1)].split(' ')
        has = [skeleton(w) for w in words[:len(head)]] == head and len(words) > len(head)
        if s == 9:
            assert not has, 'At-Tawbah must not carry a basmala'
            continue
        # 95 and 97 are written «بِّسْمِ» (with shaddah) in Tanzil: match letters only
        assert has, f'surah {s}: ayah 1 lacks the basmala prefix'
        t[(s, 1)] = ' '.join(words[len(head):])
    return t, basmala


def skeleton(word: str) -> str:
    """Letters only (no harakat / Quranic marks / tatweel; alef wasla -> alef)."""
    out = []
    for ch in word:
        o = ord(ch)
        if (0x0610 <= o <= 0x061A or 0x064B <= o <= 0x065F or o == 0x0670
                or 0x06D6 <= o <= 0x06ED or 0x08D3 <= o <= 0x08FF or o == 0x0640):
            continue
        out.append('\u0627' if o == 0x0671 else ch)
    return ''.join(out)


def dart_str(s: str) -> str:
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


# Tanzil/Quran.com metadata misspell four names (hamzat al-qat' vs al-wasl):
# إبراهيم and الإنسان take hamzat qat'; الانفطار and الانشقاق are masdars of
# «انفعل» and take hamzat wasl. Everything else in the XML is used as-is.
NAME_FIXES = {14: 'إبراهيم', 76: 'الإنسان', 82: 'الانفطار', 84: 'الانشقاق'}


def gen_index(xml_path):
    root = ET.parse(xml_path).getroot()
    suras = root.find('suras').findall('sura')
    juzs = root.find('juzs').findall('juz')
    out = [
        '// GENERATED by scripts/gen_quran_data.py from Tanzil quran-data.xml — DO NOT EDIT.',
        '// Source: Tanzil Project (tanzil.net), CC BY 3.0. Surah-name hamza fixes: NAME_FIXES.',
        '',
        'class SurahInfo {',
        '  final int number;',
        '  final String name;',
        '  final int ayahCount;',
        '  final bool meccan;',
        '  const SurahInfo(this.number, this.name, this.ayahCount, this.meccan);',
        '}',
        '',
        '/// (surah, ayah) where each of the 30 juz starts.',
        'class JuzStart {',
        '  final int juz;',
        '  final int surah;',
        '  final int ayah;',
        '  const JuzStart(this.juz, this.surah, this.ayah);',
        '}',
        '',
        'const List<SurahInfo> kSurahs = [',
    ]
    total = 0
    for s in suras:
        n, ay = int(s.get('index')), int(s.get('ayas'))
        total += ay
        meccan = 'true' if s.get('type') == 'Meccan' else 'false'
        name = NAME_FIXES.get(n, s.get('name'))
        out.append(f"  SurahInfo({n}, {dart_str(name)}, {ay}, {meccan}),")
    out.append('];')
    out.append('')
    out.append(f'const int kTotalAyat = {total};')
    out.append('')
    out.append('const List<JuzStart> kJuzStarts = [')
    for j in juzs:
        out.append(f"  JuzStart({j.get('index')}, {j.get('sura')}, {j.get('aya')}),")
    out.append('];')
    (ROOT / 'lib/data/quran_index.dart').write_text('\n'.join(out) + '\n', encoding='utf-8')
    return len(suras), total


# Verse ranges used by «رقى حسب الحالة» (see lib/data/ruqyah_types_data.dart).
EXTRACTS = {
    'arafSihr': (7, 117, 119),   # الأعراف ١١٧-١١٩
    'yunusSihr': (10, 79, 82),   # يونس ٧٩-٨٢
    'tahaSihr': (20, 65, 69),    # طه ٦٥-٦٩
}


def gen_extracts(t):
    out = [
        '// GENERATED by scripts/gen_quran_data.py from assets/quran/quran-uthmani.txt',
        '// (Tanzil Uthmani 1.1) — DO NOT EDIT. test/quran_asset_test.dart re-checks',
        '// every line against the bundled asset.',
        '',
        '/// A contiguous verse range, text exactly as in the Tanzil asset.',
        'class QuranExtract {',
        '  final int surah;',
        '  final int from;',
        '  final int to;',
        '  final List<String> verses;',
        '  const QuranExtract(this.surah, this.from, this.to, this.verses);',
        '}',
        '',
    ]
    for name, (s, a, b) in EXTRACTS.items():
        out.append(f'const {name} = QuranExtract({s}, {a}, {b}, [')
        for i in range(a, b + 1):
            out.append(f'  {dart_str(t[(s, i)])},')
        out.append(']);')
        out.append('')
    (ROOT / 'lib/data/quran_extracts.dart').write_text('\n'.join(out), encoding='utf-8')


# Whole surahs used by the written ruqyah (lib/data/written_roqia_data.dart).
LONG_SURAHS = [
    ('anfalVerses', 8, 75, 'الأنفال'),
    ('dukhanVerses', 44, 59, 'الدخان'),
    ('saffatVerses', 37, 182, 'الصافات'),
    ('haqqaVerses', 69, 52, 'الحاقة'),
]


def gen_long_surahs(t, basmala):
    out = [
        '// GENERATED by scripts/gen_quran_data.py from assets/quran/quran-uthmani.txt',
        '// (Tanzil Uthmani 1.1) — DO NOT EDIT. Each verse is the asset text verbatim',
        '// followed by « ﴿N﴾»; test/quran_asset_test.dart re-checks every line.',
        '// ' + ' + '.join(f'{name} ({count})' for _, _, count, name in LONG_SURAHS),
        '',
        f'const String basmala = {dart_str(basmala)};',
    ]
    for const, s, count, _ in LONG_SURAHS:
        ayat = [t[(s, a)] for a in range(1, count + 1)]
        assert (s, count + 1) not in t, f'surah {s} has more than {count} ayat'
        out.append('')
        out.append(f'const List<String> {const} = [')
        for a, txt in enumerate(ayat, 1):
            marker = str(a).translate(AR_DIGITS)
            out.append(f'  {dart_str(txt + " ﴿" + marker + "﴾")},')
        out.append('];')
    (ROOT / 'lib/data/quran_data.dart').write_text('\n'.join(out) + '\n', encoding='utf-8')


# (const name, doc comment, SurahVerses.name, surah, first, last, show basmala)
VERIFIED = [
    ('surahAlFatiha', 'سورة الفاتحة - 7 آيات', 'سورة الفاتحة', 1, 1, 7, False),
    ('surahAlBaqarahOpening', 'أوائل سورة البقرة (1-5)', 'سورة البقرة (أول 5 آيات)', 2, 1, 5, True),
    ('ayatAlKursi', 'آية الكرسي (البقرة 255)', 'آية الكرسي', 2, 255, 255, False),
    ('surahAlBaqarahClosing', 'خواتيم سورة البقرة (285-286)', 'خواتيم سورة البقرة (285-286)', 2, 285, 286, False),
    ('surahAzZalzalah', 'سورة الزلزلة - 8 آيات', 'سورة الزلزلة', 99, 1, 8, True),
    ('surahAlQariah', 'سورة القارعة - 11 آية', 'سورة القارعة', 101, 1, 11, True),
    ('surahAlKafirun', 'سورة الكافرون - 6 آيات', 'سورة الكافرون', 109, 1, 6, True),
    ('surahAlIkhlas', 'سورة الإخلاص - 4 آيات', 'سورة الإخلاص', 112, 1, 4, True),
    ('surahAlFalaq', 'سورة الفلق - 5 آيات', 'سورة الفلق', 113, 1, 5, True),
    ('surahAnNas', 'سورة الناس - 6 آيات', 'سورة الناس', 114, 1, 6, True),
    ('taHaMountains', 'آيات من سورة طه (105-107)', 'آيات من سورة طه', 20, 105, 107, False),
    ('hudFloodVerse', 'آية من سورة هود (44)', 'آية من سورة هود', 11, 44, 44, False),
]

VERIFIED_CLASSES = """/// نموذج آية قرآنية واحدة.
class Verse {
  final int number;
  final String text;
  const Verse(this.number, this.text);

  /// النص مع علامة رقم الآية بالأرقام العربية ﴿N﴾.
  String get withMarker {
    final arabicNum = number.toString().split('').map((d) {
      const map = {'0':'٠','1':'١','2':'٢','3':'٣','4':'٤','5':'٥','6':'٦','7':'٧','8':'٨','9':'٩'};
      return map[d] ?? d;
    }).join();
    return '$text ﴿$arabicNum﴾';
  }
}

/// مجموعة آيات من سورة معينة.
class SurahVerses {
  final String name;
  final int surahNumber;
  final String? basmala; // null للسور التي لا تبدأ بالبسملة
  final List<Verse> verses;

  const SurahVerses({
    required this.name,
    required this.surahNumber,
    required this.verses,
    this.basmala,
  });
}
"""


def gen_verified(t, basmala):
    out = [
        '// GENERATED by scripts/gen_quran_data.py from assets/quran/quran-uthmani.txt',
        '// (Tanzil Uthmani 1.1, SHA-256 pinned in test/quran_asset_test.dart) — DO NOT EDIT.',
        '// Every verse is the asset text byte for byte; scripts/verify_quran.py re-checks it.',
        '// To add verses: extend VERIFIED in the generator and re-run it.',
        '',
        VERIFIED_CLASSES,
        f'const String basmalaUthmani = {dart_str(basmala)};',
    ]
    for const, doc, name, s, a, b, show in VERIFIED:
        assert (s, b) in t
        out += ['', f'/// {doc}', f'const {const} = SurahVerses(',
                f'  name: {dart_str(name)},', f'  surahNumber: {s},']
        if show:
            out.append('  basmala: basmalaUthmani,')
        out.append('  verses: [')
        for n in range(a, b + 1):
            out.append(f'    Verse({n}, {dart_str(t[(s, n)])}),')
        out += ['  ],', ');']
    (ROOT / 'lib/data/verified_quran.dart').write_text('\n'.join(out) + '\n', encoding='utf-8')


if __name__ == '__main__':
    t, basmala = load_quran()
    assert len(t) == 6236, len(t)
    if len(sys.argv) > 1:
        n, total = gen_index(sys.argv[1])
        assert (n, total) == (114, 6236), (n, total)
    gen_extracts(t)
    gen_long_surahs(t, basmala)
    gen_verified(t, basmala)
    print('ok: 6236 ayat; extracts:', ', '.join(EXTRACTS),
          '; long surahs:', ', '.join(c for c, *_ in LONG_SURAHS))
