#!/usr/bin/env python3
"""Generate lib/data/after_prayer_data.dart from scripts/ref/hisn_after_prayer.json
(Hisn al-Muslim, «الأذكار بعد السلام من الصلاة»).

The dhikr wording is cut from the reference text, never retyped. Quran passages
(آية الكرسي، المعوذات) are NOT taken from it: the app uses the verified KFGQPC text.
`--check` regenerates in memory and fails if the Dart file differs.
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'scripts/ref/hisn_after_prayer.json'
OUT = ROOT / 'lib/data/after_prayer_data.dart'

items = {a['id']: a['text'] for a in json.load(open(SRC, encoding='utf-8'))['array']}


def clean(t: str) -> str:
    t = t.strip().replace('((', '').replace('))', '').replace(',', '،')
    t = re.sub(r'\s*\([^()]*\)', '', t)      # (ثلاثاً) etc.
    t = re.sub(r'\s*\[[^\]]*\]', '', t)      # [ثلاثاً]
    t = re.sub(r'[\s.]+$', '', t)
    return ' '.join(t.split())


def lit(s: str) -> str:
    assert "'" not in s and '\\' not in s and '$' not in s, s
    return "'" + s + "'"


# ١ — الاستغفار ثلاثاً ثم «اللهم أنت السلام»
t1 = items[1]
head, tail = t1.replace('((', '', 1).split(')', 1)   # "أستغفر الله (ثلاثاً" | " اللهم أنت السلام…))."
istighfar, salam = head.rsplit('(', 1)[0].strip(), clean(tail)
# ٤ — التسبيح والتحميد والتكبير ٣٣ ثم تمام المئة
t4 = items[4]
head, tail = t4.replace('((', '', 1).split(')', 1)
tasbih_part, tamam = head.rsplit('(', 1)[0].strip(), clean(tail)
tasbih = [p.strip() for p in re.split(r'،\s*(?:وَ)?', tasbih_part)]
assert len(tasbih) == 3, tasbih
t7 = clean(items[7].split('))')[0] + '))')
t8 = clean(items[8].split('))')[0] + '))')

def dhikr(title, repeat, text, source, note=None):
    n = f",\n      note: {lit(note)}" if note else ''
    return f"""    GeneralRuqyahItem(
      title: {lit(title)},
      repeat: {repeat},
      source: {lit(source)}{n},
      blocks: [
        RuqyahBlock(lines: [{lit(text)}]),
      ],
    ),
"""

body = ''
body += dhikr('الاستغفار', 3, istighfar, 'رواه مسلم')
body += dhikr('اللهم أنت السلام', 1, salam, 'رواه مسلم')
body += dhikr('لا مانع لما أعطيت', 1, clean(items[2]), 'متفق عليه',
              note='تُقال الجملة الأولى (لا إله إلا الله وحده… قدير) ثلاثاً ثم يُكمل الدعاء')
body += dhikr('لا حول ولا قوة إلا بالله', 1, clean(items[3]), 'رواه مسلم')
body += dhikr('التسبيح', 33, tasbih[0], 'رواه مسلم')
body += dhikr('التحميد', 33, tasbih[1], 'رواه مسلم')
body += dhikr('التكبير', 33, tasbih[2], 'رواه مسلم')
body += dhikr('تمام المئة', 1, tamam, 'رواه مسلم', note='يُختم به التسبيح والتحميد والتكبير')
body += """    GeneralRuqyahItem(
      title: 'آية الكرسي',
      subtitle: 'البقرة (٢٥٥)',
      repeat: 1,
      isQuran: true,
      source: 'رواه النسائي في عمل اليوم والليلة',
      blocks: [
        RuqyahBlock(
          heading: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
          lines: verseLines(ayatAlKursi),
        ),
      ],
    ),
    GeneralRuqyahItem(
      title: 'المعوذات',
      subtitle: 'الإخلاص والفلق والناس',
      repeat: 1,
      isQuran: true,
      source: 'رواه أبو داود والنسائي والترمذي',
      note: 'تُقرأ بعد كل صلاة؛ وتُكرَّر ثلاثاً بعد الفجر والمغرب',
      blocks: muawwidhatBlocks,
    ),
"""
body += dhikr('التهليل عشراً', 10, t7, 'رواه الترمذي وأحمد',
              note='بعد صلاتي المغرب والصبح')
body += dhikr('علماً نافعاً', 1, t8, 'رواه ابن ماجه', note='بعد السلام من صلاة الفجر')

out = f"""// GENERATED by scripts/gen_after_prayer.py — لا تعدّل يدوياً.
// المصدر: «حصن المسلم» (سعيد بن علي بن وهف القحطاني) — «الأذكار بعد السلام من الصلاة».
// آية الكرسي والمعوذات من النص العثماني الموثّق `verified_quran.dart`.

import 'general_ruqyah_data.dart';
import 'verified_quran.dart';

/// أذكار ما بعد الصلاة المفروضة بترتيب «حصن المسلم».
List<GeneralRuqyahItem> afterPrayerItems() => [
{body}  ];
"""
def _skeleton(t: str) -> str:
    t = re.sub('[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED\u0640]', '', t)
    t = t.replace('أ', 'ا').replace('إ', 'ا').replace('آ', 'ا').replace('ٱ', 'ا')
    return ' '.join(re.sub('[^ء-ي ]', ' ', t).split())


if '--verify' in sys.argv:
    # python3 scripts/gen_after_prayer.py --verify hisn_25.json
    # (https://www.hisnmuslim.com/api/ar/25.json — the official chapter)
    off = json.load(open(sys.argv[sys.argv.index('--verify') + 1], encoding='utf-8-sig'))
    off_items = list(off.values())[0]
    bad = 0
    for it in off_items:
        # الآيات (٧٠، ٧١) تأتي من النص العثماني الموثّق؛ تُقارَن بالمرجع فقط.
        ref = items[it['ID'] - 65]
        if _skeleton(it['ARABIC_TEXT']) != _skeleton(ref):
            print('MISMATCH id', it['ID']); bad += 1
    out_text = OUT.read_text(encoding='utf-8')
    for name, txt in [('istighfar', istighfar), ('salam', salam), ('t2', clean(items[2])),
                      ('t3', clean(items[3])), ('tamam', tamam), ('t7', t7), ('t8', t8)] + \
                     [(f'tasbih{i}', x) for i, x in enumerate(tasbih)]:
        if lit(txt) not in out_text:
            print('NOT IN DART:', name); bad += 1
        if _skeleton(txt) not in _skeleton(' '.join(clean(i['ARABIC_TEXT']) for i in off_items)):
            print('NOT IN OFFICIAL:', name); bad += 1
    print('official chapter matches' if not bad else f'{bad} problem(s)')
    sys.exit(1 if bad else 0)

if '--check' in sys.argv:
    if OUT.read_text(encoding='utf-8') != out:
        print('after_prayer_data.dart is stale — run scripts/gen_after_prayer.py'); sys.exit(1)
    print('after_prayer_data.dart up to date')
else:
    OUT.write_text(out, encoding='utf-8'); print('wrote', OUT)
